spring:
  zipkin:
    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      percentage: 1.0
server:
  port: 9511
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/