server:
  port: 8000
spring:
  application:
    name: microservice-provider-userservice
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.pollux: ERROR
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
