server:
  port: 8050
spring:
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cnodin/spring-cloud-microservice-study
          search-paths: config-repo
          username: cnodin@gmail.com
          password: jbgsnmm38
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/